name: laplace_approximation
subset_of_weights: 'last_layer'
hessian_structure: 'diag'
optimization_method: 'gridsearch'
prediction_type: 'glm'
link_approximation: 'mc'
sample_size: 100
grid_size: 100
la_batch_size: 8
train_size: 10000
test_size: 2000
ood_threshold: 0.30
misclassify_threshold: 0.35