name: "tta"
sample_size: 50
ood_threshold: 1.45
misclassify_threshold: 1.45

  
augmentation:
  _type: Compose
  transforms:
    - _type: RandomChoice
      transforms:
        - _type: RandomAffine
          degrees: 0
          scale: [0.9, 1.1]
        - _type: RandomRotation
          degrees: [-15, 15]
    # - _type: RandomHorizontalFlip
    # - _type: RandomVerticalFlip
