defaults:
  - dataset: isic
  - model: mlp
  - method: mc_dropout
  - optimizer: sgd
  - experiment: isic_drop
  - _self_

seed: 11111
weighted: False

setup_only: false
methods_to_run: []

data:
  root: ${hydra:runtime.cwd}/data

output:
  save_model: true
  save_metrics: true
  run_id: ${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: ${hydra:runtime.cwd}/results/${now:%Y-%m-%d}/${experiment.name}/${method.name}/${now:%H-%M-%S}
